export const CALCULATE_REPAYMENT = 'CALCULATE_REPAYMENT';
export const ADD_LOAN = 'ADD_LOAN';
export const EDIT_LOAN = 'EDIT_LOAN';
export const DELETE_LOAN = 'DELETE_LOAN';
export const UPDATE_MONTHLY_PAYMENT = 'UPDATE_MONTHLY_PAYMENT';

